### ISSUE TITLE
Broken with PHP7

### ISSUE THREAD

**Issue by POpus** [POpus/dokuwiki-groupmail#8]
Plugin no longer works if dokuwiki is running under **PHP7** because of **ereg/eregi** commands removed from it. Attached is a new syntax.php with the commands replaced with **preg_match**. I didn't change author or version. Hoping the author looks it over and implements it.

If so, please make date in plugin info match dokwiki info page so extentions page in the Wiki correctly identifies the versions. Right now it says there is an update available even though there isn't one.

[new_syntax.php.txt](https://github.com/bzfwunde/dokuwiki-groupmail/files/2104037/new_syntax.php.txt)

**Comment by jFMd21** [comment]
Thank you very much for this fix, POpus!! This kind of made my day!!

Unfortunately the author doesn't seem to be maintaining this plugin anymore, would you be willing to take over it? I bet this would be very much appreciated, since there have been some feature request in the recent years... ;-)

I would love to help testing, documenting etc. but I am not able to do programming as well.

Cheers, jFMd21

**Comment by bzfwunde** [comment]
On Thursday, June 14, 2018 14:20:10 POpus wrote:
> Plugin no longer works if dokuwiki is running under **PHP7** because of
> **ereg/eregi** commands removed from it. Attached is a new syntax.php with
> the commands replaced with **preg_match**. I didn't change author or
> version. Hoping the author looks it over and implements it.
> 
> If so, please make date in plugin info match dokwiki info page so extentions
> page in the Wiki correctly identifies the versions. Right now it says there
> is an update available even though there isn't one.
> 
> [new_syntax.php.txt](https://github.com/bzfwunde/dokuwiki-groupmail/files/21
> 04037/new_syntax.php.txt)


Sorry, I don't have time to maintain the plugin any longer.  I would be
happy if someone were found to take over.

Thanks,

Roland

**Comment by POpus** [comment]
**jFMd21:** Making your day kind of made my day! - thxs

**Roland:** I may be willing to take it over, but I've never done that before so a bit leary about it. Can't say I know much about how plugins work or dokuwiki for that matter. If I find some time I'll look over the code and see if I can figure out out to add a feature request. Is there any formal way of taking over the code?

**Comment by bzfwunde** [comment]
On Monday, June 25, 2018 11:04:12 POpus wrote:
> **jFMd21:** Making your day kind of made my day! - thxs
> 
> **Roland:** I may be willing to take it over, but I've never done that
> before so a bit leary about it. Can't say I know much about how plugins
> work or dokuwiki for that matter. If I find some time I'll look over the
> code and see if I can figure out out to add a feature request. Is there any
> formal way of taking over the code?

To tell you the truth, I just got started from an existing mailing plugin and
added support for groupmail.  I really don't know much either.  This should be 
comforting:  You can get something going without much knowledge :).

Good luck and thanks for volunteering!

Roland

**Comment by POpus** [comment]
Roland: It looks like you have to initiate the transfer of the repository to me:

https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/
